### ISSUE TITLE
gradle files?

### ISSUE THREAD

**Issue by jhanc97** [meh430/RedditWall#1]
hello, a query, and the .gradle files ?. Android studio does not sync.

**Comment by mehulpillai30** [comment]
Hey, this app is just a personal project I made for the purpose of learning so I didn't really expect anyone else to really see or use it. Thanks for the interest though. I've made a new branch that should have all the required files. Hope that helps.

**Comment by jhanc97** [comment]
@meh430 Thank you very much, by the way the interface was beautiful.
