### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by ghost** [meh430/RedditWall#2]
Download images by post link.

**Comment by mehulpillai30** [comment]
Hey there! Sorry for the late reply, I've been busy with work and school. If you're still interested, I've actually rewritten the app. You can find it [here](https://github.com/meh430/RedditWalls-rewrite). In the search bar, you can post a link which should let you open up the image in the post if there is one. From there, you could download the image if you have given storage permissions. The app also supports deeplinks now so if you click a post link, the app should show up as on option to open that link. Hope that helps!
